### ISSUE TITLE
can't run the train step in model.py

### ISSUE THREAD

**Issue by mingzhaochina** [tperol/ConvNetQuake#4]
First thank you for share this great code!
I tried to use the trained model of cluster 6 to classify my own data,however,the result is not ideal:for 10000 events it identify about 2000.
 So I tried to train the model myself by running:
./bin/train --dataset data/6_clusters/detection/train/ --checkpoint_dir output/convnetquake_6/ --n_clusters 6, in the program tflib/model.py line 44:
**data = sess.run(tofetch, options=run_options, run_metadata=run_metadata)**
will stop and give this message:
2017-11-29 23:07:44.380113: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Name: <unknown>, Feature: end_time (data type: int64) is required but could not be found.

It seems to be a version error,any version higher than 0.11 won't work.

**Comment by mingzhaochina** [comment]
the problem happens when running to the **_train_step** function in **model.py**,even if I installed a lower version(tensorflow 0.11),it has the same problem when goes to the phase:
**data = sess.run(tofetch, options=run_options, run_metadata=run_metadata)**

**Comment by lovelytt0** [comment]
Yes, I met the same problem

**Comment by mingzhaochina** [comment]
It is a problem related to the dataset,some tfrecord file is not complete.You can build your own dataset.See an example on my github:

https://github.com/mingzhaochina/ConvNetQuake

**Comment by zhyw86** [comment]
@mingzhaochina 
I met another error with the 'step' parameter in tflib/model.py. I used your code but it did not work. 

Initializing all variables.
Starting data threads coordinator.
Starting optimization.
2018-08-20 22:41:10.265956: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Feature: end_time (data type: int64) is required but could not be found.
2018-08-20 22:41:10.310716: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Feature: end_time (data type: int64) is required but could not be found.
Shutting down data threads.
Traceback (most recent call last):
  File "./train", line 88, in <module>
    main(args)
  File "./train", line 70, in main
    summary_step=10)
  File "/home/fl/SRL/ConvNetQuake/another/ConvNetQuake/tflib/model.py", line 277, in train
    print 'Training completed at step {}.'.format(step)
UnboundLocalError: local variable 'step' referenced before assignment

**Comment by mingzhaochina** [comment]
I don't know exactly what was happening.But it shouldn't be a problem of
the code.I encounter this error message before,and it turned out to be the
problem of the input data.

Hope that will help you


2018-08-21 10:49 GMT+08:00 zhyw86 <notifications@github.com>:

**Comment by zhyw86** [comment]
@mingzhaochina 

You were right. We can use the synthetic data for training but not the 6 or 50 cluster data. 

Thanks for the information.

**Comment by jinchengxu** [comment]
@mingzhaochina I met the same problem. Have you fixed this problem of the input data?
